version: '3.3'
services:
  ascent-discovery:
    image: ascent/ascent-discovery
    hostname: ascent-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=aws-ci
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
        - ascentnet
    ports:
        - "8761"
  
networks:
  ascentnet:
    driver: overlay