version: '3.4'
services:
  ascent-discovery:
    image: ascent/ascent-discovery:${RELEASE_VERSION:-latest}
    hostname: ascent-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker-demo}
      - VAULT_ADDR=${VAULT_ADDR:-http://vault:8200}
      - VAULT_TOKEN=${VAULT_TOKEN:-vaultroot}
      - discovery.server.peer.name=ascent-discovery-peer
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 60s
        monitor: 60s
        failure_action: pause

    networks:
        - ascentnet
    ports:
        - "${PORT:-8761:8761}"
    healthcheck:
      test: ["CMD", "/healthcheck", "--url", "https://localhost:8761/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s

  ascent-discovery-peer:
    image: ascent/ascent-discovery:${RELEASE_VERSION:-latest}
    hostname: ascent-discovery-peer
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker-demo}
      - VAULT_ADDR=${VAULT_ADDR:-http://vault:8200}
      - VAULT_TOKEN=${VAULT_TOKEN:-vaultroot}
      - discovery.server.peer.name=ascent-discovery
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 60s
        monitor: 60s
        failure_action: pause
    networks:
      - ascentnet
    ports:
      - 8761
    healthcheck:
      test: ["CMD", "/healthcheck", "--url", "https://localhost:8761/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 60s
  
networks:
  ascentnet:
    external:
      name: ascentnet