server:
  port: ${discovery.server.port:8761}
info:  
  build:
    version:  "@project.version@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
security:
  basic:
    enabled: true
  user:
      name: ${discovery.username:eureka}
      password: ${discovery.password:default}
eureka:
  instance:
    hostname: ${server.name:localhost}
    metadataMap:
      hostname : ${eureka.instance.hostname}
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: true
    
---

spring:
    profiles: aws-ci, aws-stage, aws-prod

eureka: 
  shouldBatchReplication: true
  #In the AWS cloud environment, pass in the java commandline property -Deureka.datacenter=cloud so that 
  #the Eureka Client/Server knows to initialize the information specific to AWS cloud.
  datacenter: cloud
  #client: 
  # registerWithEureka: true
  # serviceUrl:
  #   defaultZone: http://${discovery.username:eureka}:${discovery.password:default}@${discovery.server.peer1.name:ascent-discovery}:${discovery.server.port:8761}/eureka/,http://${discovery.username:eureka}:${discovery.password:default}@${discovery.server.peer2.name:ascent-discovery}:${discovery.server.port:8761}/eureka/
---
spring:
    profiles: aws-prod
eureka: 
  environment: prod