version: "3.3"
services:
  ascent-discovery:
    image: ascent/ascent-discovery
    build:
      context: ..
    hostname: ascent-discovery
    ports:
     - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
      - discovery.server.peer.name=ascent-discovery-peer
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    networks:
        - ascentnet
  ascent-discovery-peer:
    image: ascent/ascent-discovery
    build: 
      context: ..
    hostname: ascent-discovery-peer
    ports:
     - "8861:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
      - discovery.server.peer.name=ascent-discovery
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    depends_on:
      - ascent-discovery
    networks:
        - ascentnet
networks:
  ascentnet: 
    driver: bridge
